#!/bin/bash

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Connecting to RosAria..."
rosrun rosaria RosAria &
pid="$! $pid"
sleep 3s

#echo "Launching publishers..."

#rosrun pioneer_test pioneer3dx_odometry_publisher &
#pid="$! $pid"

#roslaunch rplidar_ros rplidar.launch &
#pid="$! $pid"

#rosrun pioneer_test laser_tf_broadcaster &
#pid="$! $pid"

#rosrun pioneer_test rplidar_laser_publisher &
#pid="$! $pid"

#rosrun pioneer_test rplidar_laser_republisher &
#pid="$! $pid"

echo "Launching sensors..."
roslaunch pioneer_test pioneer_sensors.launch &
pid="$! $pid"

sleep 3s

echo "Launching navigation stack..."
roslaunch nav_bundle nav_bundle.launch &
pid="$! $pid"

sleep 3s

echo "Launching pioneer controller..."
roslaunch pioneer_test pioneer_controller.launch &

sleep 3s

echo "Launching rviz..."
rosrun rviz rviz -d "$(rospack find pioneer_test)/pioneer_test_rviz_config.rviz" &
pid="$! $pid"

sleep 1s

trap "echo Killing all processes.; kill -2 $pid; exit" SIGINT SIGTERM

sleep 24h
